clc;
clear;
a=4.315;
b=2.495;
l=3.675;
r=0.950;
h=4.3195;
i=1.0281;
lamda=r/l;
omiga=7.6*pi/30;
fai=linspace(0,2*pi,144);
s1=r*((1-cos(fai))+1/lamda*(1-sqrt(1-(lamda*sin(fai)).^2)))*a/b;
s2=a*(pi/2-acos((b^2-l^2+(i+r*sin(fai)).^2+(h-r*cos(fai)).^2)./(2*b*sqrt((i-r*sin(fai)).^2+(h-r*cos(fai)).^2)))-atan((i+r*sin(fai))./(h-r*cos(fai))));
load fj1s;
m=find(fj1s==0,1);
fj1s=[fj1s(m:length(fj1s));fj1s(1:m-1)];
figure;
plot(s1,'--');
hold on;
plot(s2,'-');
plot(fj1s,'.-');
legend('滑块法','解析法','实测值');
xlabel('采样点');
ylabel('位移/m');
title('位移曲线');
grid on;

s=sqrt((i+r*sin(fai)).^2+(h-r*cos(fai)).^2);
delta=atan((i+r.*sin(fai))./(h-r.*cos(fai)));
gama=acos((b^2+s.^2-l^2)./(2*b*s));
dsdt=r*omiga*sin(delta+fai);
deldt=r*omiga*cos(delta+fai)./s;
dgamdt=-1./sin(gama).*(s.^2-b^2+l.^2)./(2*b*s.^2).*dsdt;

v1=-a*(dgamdt+deldt);
v2=omiga*r*(sin(fai)+lamda*sin(2*fai)./(2*sqrt(1-lamda^2.*sin(fai).^2)))*a/b;
figure;
plot(v1,'-');
hold on;
plot(v2,'--');
legend('解析法','滑块法');
xlabel('采样点');
ylabel('速度(m/s)');
title('速度曲线');
grid on;

xx=1-lamda^2*sin(fai).^2;
ff=delta+fai;
a1=a*r*omiga*((cos(ff)./sin(gama).*(deldt+omiga)-sin(ff)./sin(gama)./tan(gama).*dgamdt).*(s.^2-b^2+l^2)./(2*b*s.^2)+sin(ff)./sin(gama).*(b^2-l^2)/b./s.^3.*dsdt+sin(ff)./s.*(deldt+omiga)+cos(ff)./s.^2.*dsdt)/2;
a2=omiga^2*r*(cos(fai)+lamda*cos(2*fai)./sqrt(xx)+lamda^3*sin(2*fai).^2./(4*xx.^1.5));
figure;
plot(a1,'-');
hold on;
plot(a2,'--');
legend('解析法','滑块法');
xlabel('采样点');
ylabel('加速度(m/s^2)');
title('加速度曲线');
grid on;
